#!/bin/sh

# Forward signals to the child process
trap 'kill -TERM $PID' TERM INT

# Start the main process
exec 2>&1
exec bash /data/apps/dbus-serialbattery/start-serialbattery.sh TTY &

# Capture the PID of the child process
PID=$!

# Wait for the child process to exit
wait $PID

# Capture the exit status
EXIT_STATUS=$?

# Exit with the same status
exit $EXIT_STATUS
